name: flutter_super_aslan_app
description: My new Flutter Super Aslan  app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.1
  intl: ^0.20.2
  app_ui:
    path: packages/app_ui
  repository:
    path: packages/repository
  api_http_client:
    path: packages/api_http_client
  http_client:
    path: packages/http_client
  storage:
    path: packages/storage/storage
  token_storage:
    path: packages/storage/token_storage
  persistent_storage:
    path: packages/storage/persistent_storage
  shared_preferences: ^2.3.4
  dio: ^5.9.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_iconly: ^1.0.2
  loading_indicator: ^3.1.1
  table_calendar: ^3.2.0
  collection: ^1.19.1
  image_picker: ^1.2.1
  file_picker: ^10.3.8
  record: ^6.1.2
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  http: ^1.6.0
dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
